config/routes.rb
Rails.application.routes.draw do
  root "user#index" 
  get "user/index"     => 'user#index'
  post "user/sign_in"  => 'user#sign_in'
  get "user/sign_out" =>'user#sign_out'
  
  get"supervisor/index"  => 'supervisor#index'
  get "receptionnist/index"  => 'receptionnist#index'

  post "supervisor/creat" => 'user#creat_receptionist'
  get "supervisor/new_rec" => 'supervisor#creat'
  get "supervisor/update" => 'supervisor#update'
  post "supervisor/getupdate" => 'user#update'
  get  "supervisor/show_receptionist" => 'supervisor#show_receptionist'
  post "supervisor/add_type" => 'supervisor#add_equipment_type'
  get "supervisor/add_equip_type"=>'supervisor#add_equip_type' 
  get "supervisor/back"=>'supervisor#back'
  post "supervisor/add_equipattr"=>'supervisor#add_equipattr'
  get "supervisor/show_equipment" =>'supervisor#show_equip'
  get "supervisor/show_select" => 'supervisor#show_select'
  
  get  "equipment/update/:id"=>'equip#update_cost'
  get  "equipment/update_bpl/:id"=>'equip#update_cost_bpl'
  get "equipment/update_othr/:id"=>'equip#update_cost_othr'
  post "equipment/new_cost" => 'equip#new_cost'
  post "equipment/new_cost_othr" => 'equip#new_cost_othr'
  post "equipment/new_cost_bpl" => 'equip#new_cost_bpl'
  post "equipment/delete/:id" =>'equip#delete'
  post "equipment/reset/:id"=>'equip#reset'

  post "receptionnist/delete/:id"=>'receptionnist#delete'
  post "receptionnist/index"=> 'receptionnist#index'

  post "person/bill"=>'person#bill'
  get "update_equip"=>'receptionnist#update_equip'
  get "cost_select"=>'receptionnist#show_price'
  get "temp_add"=>'receptionnist#temp_add'
  post "delete_item/:id"=>'receptionnist#delete_item'
  post "receptionnist/print"=>'receptionnist#print'
  post "receptionnist/cancel"=>'receptionnist#cancel'
  get "receptionnist/billno"=>'receptionnist#billno'
  post "person/billcancel"=>'person#billcancel'

  get "update_billequip"=>'person#update_billequip'
  get "cost_billselect"=>'person#cost_billselect'
  get "cancel"=>'person#cancel'
  get "report_yearly"=>'category#report_yearly'
  get "report_monthly"=>'category#report_monthly'
  get "report_daily" =>'category#report_daily'

end

app/controllers/supervisor_controller.rb
class SupervisorController < ApplicationController
   include UserHelper 
   def show_receptionist
    if current_user
   	 @details=User.where(:role=>"a")
    end
   end 

   def add_equipment_type
    #flash[:notice]="name=#{params[:type_name]}"
    if current_user
       session[:new_type]=params[:type_name]
     if params[:type_name].blank?
        flash[:error]="can't be blank"
        redirect_to supervisor_index_path
     else
        redirect_to supervisor_add_equip_type_path
     end
   end
   end

   def back
   	 redirect_to supervisor_index_path
   end 

   def add_equipattr
    if current_user
     find=Category.find_by_type_name(session[:new_type])
     if !find
       @category=Category.new()
       @category.type_name=session[:new_type]
       @category.save
       find=@category
     end
       #flash[:notice]="#{find.type_name}&#{find.id}"
       if find
         @equipment=find.equips.new(equip_params)
         #@equipment.category_id=@category.id
         #flash[:notice]="#{@equipment.name}&#{find.id}"
         if @equipment.save
           flash[:notice]="successfully added #{@equipment.name}"
         else
            flash[:error]=@equipment.errors.full_messages.to_sentence
         end
       else
          flash[:error]=find.errors.full_messages.to_sentence
       end
     end
       redirect_to :back 
   end
   
   def show_equip
    if current_user
       if params[:equip_type]
         val=params[:equip_type]
         session[:e_type]=val[:type_id]
       end
       #flash[:notice]="hello #{val[:type_id]}"
       #session[:e_type]=val[:type_id]
       if session[:e_type].blank?
          flash[:error]="can't select be blank"
          redirect_to supervisor_index_path
       else
         @cat=Category.find_by_id(session[:e_type])
         @equip_total=Equip.where(:category_id =>session[:e_type])
         #redirect_to supervisor_show_select_path
       end
     end
   end
   
   def show_select
       #redirect_to supervisor_show_equipment_path
   end
   private
   def equip_params
       params.require(:equip).permit(:serial_no,:name,:cost,:bpl,:other,:usage)
   end
end

app/helpers/supervisor_helper.rb
module SupervisorHelper
end

app/views/supervisor/add_equip_type.html.erb
<h1>add type</h1>
<%= link_to supervisor_back_path do%>
      <span>back</span>
<%end%>
<%= form_for @equip=Equip.new, :url=>supervisor_add_equipattr_path, method: :post do |e|%>
     <%=e.label :serial_no %><br>
     <%= e.text_field :serial_no %><br><br>
     <%=e.label :name %><br>
     <%= e.text_field :name %><br><br>
     <%=e.label :apl_cost%><br>
     <%= e.text_field :cost %><br><br>
     <%=e.label :bpl_cost%><br>
     <%= e.text_field :bpl %><br><br>
     <%=e.label :other%><br>
     <%= e.text_field :other %><br><br>
     <%= e.hidden_field :usage, :value=>0 %>
  <%= e.submit "Add",:class=>"btn btn-primary" %>
  <%end%>

app/views/supervisor/creat.html.erb
<h1>create receptionnist</h1><br><br>
 <%= link_to supervisor_index_path do%>
      <span>back</span>
 <%end%>
   <%= form_for @user=User.new, :url=>supervisor_creat_path, method: :post do |form| %>
   <%= form.label :name %><br>
   <%= form.text_field :name %><br><br>
 
   <%= form.label :username %><br>
   <%= form.text_field :username %><br><br>

   <%= form.label :password %><br>
   <%= form.password_field :password %><br><br>

   <%= form.label :password_confirmation %><br>
   <%= form.password_field :password_confirmation %><br><br>
 
   <%= form.label :Email %><br>
   <%= form.email_field :email %><br><br> 

   <%= form.label :phone_number %><br>
   <%= form.number_field :phone %><br><br>

   <%= form.hidden_field :role, :value=>"a" %>

   <%= form.submit "Add",:class=>"btn btn-primary" %>

<% end %>

app/views/supervisor/index.html.erb
<h1>Hello <%=current_user.name%></h1>
<!--sign out button start--> 
    <%= link_to  user_sign_out_path,:class=>"btn" do%>
       <span> Logout</span>
    <%end%>
<!--signout button stop-->
<!--adding new receptionist-->
  <div style="float:right;">
    <h3>Update Details</h3>
      <%=link_to  supervisor_update_path,:class=>"btn btn-primary"  do%>
          <span>update details</span>
      <%end%>

    <h3>Report Generation</h3>
         <div class="btn-group">
           <%= link_to  report_yearly_path,:class=>"btn btn-primary" do%>
             <span> Yearly</span>
           <%end%>
           <%= link_to  report_monthly_path,:class=>"btn btn-primary" do%>
                <span> Monthly</span>
           <%end%>
           <%= link_to  report_daily_path,:class=>"btn btn-primary" do%>
              <span> Daily</span>
           <%end%>
        </div>
    <h3>Show equipments</h3>
      <%= form_tag(supervisor_show_equipment_path, method: :get) do%>
          <%=select("equip_type", "type_id", Category.all.collect {|p| [ p.type_name, p.id ] }, {prompt: 'select type name'})%>
          <%=submit_tag "Go!",:class=>"btn btn-success" %>
      <%end%>
  </div>

  <h3>Add New Receptionist</h3>
      <%= link_to supervisor_new_rec_path ,:class=>"btn btn-primary" do%>
        <span>create receptionist</span>
      <%end%>

  <h3>Show Receptionist</h3>
      <%= link_to supervisor_show_receptionist_path,:class=>"btn btn-primary"  do%>
        <span>show</span>
      <%end%>

  <h3>Add New Type of Equipment</h3>
      <%= form_tag(supervisor_add_type_path, method: :post) do%>
        <%=label_tag :type_name %><br>
        <%= text_field_tag :type_name %>
        <%=submit_tag "Add", :class=>"btn btn-primary"%>
      <%end%>

app/views/supervisor/show_equip.html.erb
<h1>The Equipments in Database Are</h1>
<%= link_to supervisor_index_path,:class=>"btn btn-primary" do%>
      <span style="color:white">&larr;back</span>
 <%end%>
 <br><br>
 <%if @cat%>  
  <h2><%=@cat.type_name%></h2>
  
  <table class="table table-hover table-bordered">
  <tr>
    <th>serial no</th>
    <th>name</th>
    <th>apl cost</th>
    <th>bpl cost</th>
    <th>others</th>
    <th>usage</th>
    <th>change cost</th>
    <th>reset usage</th>
    <th>delete</th>
  </tr>
 
  <% @equip_total.each do |d| %>
    <tr>
      <td><%= d.serial_no %></td>
      <td><%= d.name %></td>
      <td><%= d.cost %></td>
      <td><%= d.bpl %></td>
      <td><%= d.other%></td>
      <td><%= d.usage%></td>
      <td>
          <%=link_to "APL","/equipment/update/#{d.id}",method: :get,:class=>"btn btn-small btn-primary"%>
          <%=link_to "BPL","/equipment/update_bpl/#{d.id}",method: :get,:class=>"btn btn-small btn-primary"%>
          <%=link_to "OTHERS","/equipment/update_othr/#{d.id}",method: :get,:class=>"btn btn-small btn-primary"%>
      </td>
      <td><%=link_to "Reset","/equipment/reset/#{d.id}",method: :post,:class=>"btn btn-small btn-info"%></td>
      <td><%=link_to "Delete","/equipment/delete/#{d.id}",method: :post,:class=>"btn btn-small btn-danger"%></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/supervisor/show_receptionist.html.erb
<h1>receptionist are shown below</h1>
 <%= link_to supervisor_index_path do%>
      <span class="btn btn-primary"><i class="icon-step-backward"></i>back</span>
 <%end%>
 <br><br>
 <table class="table table-hover table-bordered">
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Delete</th>
  </tr>
 
  <% @details.each do |d| %>
    <tr>
      <td><%= d.name %></td>
      <td><%= d.username %></td>
      <td><%= d.email %></td>
      <td><%= d.phone%></td>
      <td><%=link_to "Delete","/receptionnist/delete/#{d.id}",method: :post,:class=>"btn btn-mini btn-danger"%></td>
    </tr>
  <% end %>
</table>

app/views/supervisor/update.html.erb
<h1>update your details</h1>
 <%= link_to supervisor_index_path do%>
      <span>back</span>
 <%end%>
<%= form_for @user=User.new, :url=>supervisor_getupdate_path, method: :post do |form| %>
   <%= form.label :name %><br>
   <%= form.text_field :name %><br><br>
 
   <%= form.label :username %><br>
   <%= form.text_field :username %><br><br>

   <%= form.label :password %><br>
   <%= form.password_field :password %><br><br>

   <%= form.label :password_confirmation %><br>
   <%= form.password_field :password_confirmation %><br><br>
 
   <%= form.label :Email %><br>
   <%= form.email_field :email %><br><br> 

   <%= form.label :phone_number %><br>
   <%= form.number_field :phone %><br><br>

   <%= form.hidden_field :role, :value=>"s" %>

   <%= form.submit "Update",:class=>"btn btn-primary" %>

<% end %>