config/routes.rb
Rails.application.routes.draw do
  root "user#index" 
  get "user/index"     => 'user#index'
  post "user/sign_in"  => 'user#sign_in'
  get "user/sign_out" =>'user#sign_out'
  
  get"supervisor/index"  => 'supervisor#index'
  get "receptionnist/index"  => 'receptionnist#index'

  post "supervisor/creat" => 'user#creat_receptionist'
  get "supervisor/new_rec" => 'supervisor#creat'
  get "supervisor/update" => 'supervisor#update'
  post "supervisor/getupdate" => 'user#update'
  get  "supervisor/show_receptionist" => 'supervisor#show_receptionist'
  post "supervisor/add_type" => 'supervisor#add_equipment_type'
  get "supervisor/add_equip_type"=>'supervisor#add_equip_type' 
  get "supervisor/back"=>'supervisor#back'
  post "supervisor/add_equipattr"=>'supervisor#add_equipattr'
  get "supervisor/show_equipment" =>'supervisor#show_equip'
  get "supervisor/show_select" => 'supervisor#show_select'
  
  get  "equipment/update/:id"=>'equip#update_cost'
  get  "equipment/update_bpl/:id"=>'equip#update_cost_bpl'
  get "equipment/update_othr/:id"=>'equip#update_cost_othr'
  post "equipment/new_cost" => 'equip#new_cost'
  post "equipment/new_cost_othr" => 'equip#new_cost_othr'
  post "equipment/new_cost_bpl" => 'equip#new_cost_bpl'
  post "equipment/delete/:id" =>'equip#delete'
  post "equipment/reset/:id"=>'equip#reset'

  post "receptionnist/delete/:id"=>'receptionnist#delete'
  post "receptionnist/index"=> 'receptionnist#index'

  post "person/bill"=>'person#bill'
  get "update_equip"=>'receptionnist#update_equip'
  get "cost_select"=>'receptionnist#show_price'
  get "temp_add"=>'receptionnist#temp_add'
  post "delete_item/:id"=>'receptionnist#delete_item'
  post "receptionnist/print"=>'receptionnist#print'
  post "receptionnist/cancel"=>'receptionnist#cancel'
  get "receptionnist/billno"=>'receptionnist#billno'
  post "person/billcancel"=>'person#billcancel'

  get "update_billequip"=>'person#update_billequip'
  get "cost_billselect"=>'person#cost_billselect'
  get "cancel"=>'person#cancel'
  get "report_yearly"=>'category#report_yearly'
  get "report_monthly"=>'category#report_monthly'
  get "report_daily" =>'category#report_daily'

end

app/controllers/receptionnist_controller.rb
class ReceptionnistController < ApplicationController
	def index
		if(params[:flag])
	     
		end
		@person=Person.new
	    @bill=Person.new
		@categories=Category.all
		@equips=Equip.all
		session[:billno]=nil
	end

   	def delete
        id=User.find_by_id(params[:id])
 		id.destroy
 		redirect_to :back
 	end	
 	def update_equip
 		category=Category.find(params[:category_id])
 		@equips=category.equips.map { |e| [e.name,e.id] }.insert(0,"select an equipment")
 	end
 	def show_price
        t=Tempperson.find(1)
        if t.bench=="apl"
 	       @cost=Equip.find(params[:equip_id]).cost
       elsif t.bench=="bpl"
           @cost=Equip.find(params[:equip_id]).bpl
       else
          @cost=Equip.find(params[:equip_id]).other
      end
 	end
 	def temp_add
 		@temp=Temp.new
        cat=Category.find_by_id(params[:category_id])
        @temp.category=cat.type_name
        eqp=Equip.find_by_id(params[:equip_id])
        @temp.equip=eqp.name
        @temp.qty=params[:quantity]
        @temp.unit_price=params[:unit_cost]
        @temp.total_price=params[:total_cost]
        @temp.save
        s=Sum.find(1)
        s.total=s.total+@temp.total_price
        s.save
 	end
 	def delete_item
 		del=Temp.find_by_id(params[:id])
 		s=Sum.find(1)
 		s.total=s.total-del.total_price
 		s.save
 		name=del.equip
 		obj=Equip.find_by_name(name)
 		obj.usage=obj.usage-del.qty
 		obj.save
 		del.destroy
 		#flash[:notice]="hello #{params[:temp]}"
 		redirect_to :back
 	end
 	def print
   		val=Person.where(:opno=>Tempperson.find(1).opno).last
   		#flash[:notice]="#{val.billno.to_s}"
   		path=val.billno.to_s+".txt"
   		#flash[:notice]="#{path}"
        fd=File.new(path,"w+")
        @temp=Temp.all
        fd.write("Bill No:-")
        fd.write(val.billno.to_s)
        fd.write("\nIN THE ORDER(")
        fd.write("Category 	Equipment 	Qty  Unit Cost 	Total cost)\n")
        i=0
        @temp.each do |d|
        	fd.write("(#{i+1})")
        	 i=i+1
            fd.write(d.category)
            fd.write("\t")
            fd.write(d.equip)
            fd.write("\t")
            fd.write(d.qty)
            fd.write("\t")
            fd.write(d.unit_price)
            fd.write("\t")
            fd.write(d.total_price)
            fd.write("\n")
        end
        fd.write("\n\n***********[PLEASE NOTE THIS IS A JUNK FILE DELETE AFTER USE}*********************\n")
        fd.close
   		s=Sum.find(1)
 		s.total=0
 		s.save
 		Temp.destroy_all
 		t=Tempperson.find(1)
 		t.name=""
 		t.age=""
 		t.gender=""
 		t.opno=""
 		t.ipno=""
 		t.wardno=""
 		t.address=""
 		t.save
 		redirect_to :back
 	end
 	def billno
         b=Person.new
         t=Tempperson.find(1)
        if t.name!=""&&t.age!=""&&t.gender
          	b.name=t.name
          	b.age=t.age
          	b.opno=t.opno
          	b.ipno=t.ipno
         	  b.wardno=t.wardno
         	  b.gender=t.gender
         	  b.address=t.address
         	  b.billno=params[:bill_no]
            b.bench=t.bench
         	  b.cost=Sum.find(1).total
         	  b.save
         	  @temp=Temp.all
        	  @temp.each do |t|
        		name=Equip.find_by_name(t.equip)
        		name.usage=name.usage+t.qty
        		name.save
         	end
        end
 	end
  def cancel
    Temp.destroy_all
    t=Tempperson.find(1)
    t.name=""
    t.age=""
    t.gender=""
    t.opno=""
    t.ipno=""
    t.wardno=""
    t.address=""
    t.save
    s=Sum.find(1)
    s.total=0
    s.save
    redirect_to :back
  end
end

app/helpers/receptionnist_helper.rb
module ReceptionnistHelper
end

app/views/receptionnist/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">    
     .adj1{
        width:50px;
      }     
      #cancel{
        float:right;
      } 
	</style>
</head>
<body>
<h1 id="hello">he<span style="color:red;">ll</span>o <%=current_user.name%></h1>
<!--sign out button start--> 
  <%= link_to  user_sign_out_path,:class=>"btn btn-primary",:id=>"logout" do%>
    <span> Logout</span>
  <%end%>

  <div id="cancel">
  <%= form_tag(person_billcancel_path ,method: :post) do%>
    <%=label_tag :billno%>
    <%=text_field_tag :billno%>
    <%=submit_tag "BILL-CANCEL",:class=>"btn btn-danger"%>
  <%end%>
  </div><br>
<p hidden id="hos_name" style="text-align:center;font-size:20px;font-weight:bold;"></p><br>
<!--signout button stop-->
<%@bill_no=Time.now.to_i%>
<p hidden id="bill_no" value=<%=@bill_no%>><span style="font-weight:bold;">Bill No:</span><%=@bill_no%></p>
<%@p=Tempperson.find(1)%>
<%if @p.name ==""%>
<%= form_for @person,:url=>person_bill_path ,method: :post do |e|%>
   <%=e.label :name%>:-
   <%=e.text_field :name%>
   <%=e.label :age%>:-
   <%=e.text_field :age,:class=>"adj1"%>
   <%=e.label :gender%>:-
   <%=e.text_field :gender,:class=>"adj1"%>
   <%=select("bench", "bench", options_for_select([["bpl", "bpl"], ["apl", "apl"],["other","other"]]), {prompt: 'select category'})%>
   <%=e.label :opno%>:-
   <%=e.text_field :opno,:class=>"adj1"%>
   <%=e.label :ipno%>:-
   <%=e.text_field :ipno,:class=>"adj1"%>
   <%=e.label :wardno%>:-
   <%=e.text_field :wardno,:class=>"adj1"%><br>
   <%=e.label :address%>:-
   <%=e.text_field :address%>
   <%=e.submit "process",:class=>"btn btn-success",:id=>"submit"%>
<%end%>
<%else%>
  <label>Name:-    </label>  <span><%=@p.name%></span>
  <label>Age:-     </label>  <span><%=@p.age%></span>
  <label>gender:-  </label>  <span><%=@p.gender%></span>
  <label>category:-  </label>  <span><%=@p.bench%></span>
  <label>opno:-    </label>  <span><%=@p.opno%></span>
  <label>ipno:-    </label>  <span><%=@p.ipno%></span>
  <label>wardno:-  </label>  <span><%=@p.wardno%></span>
  <label>address:- </label>  <span><%=@p.address%></span>
<%end%>
  <br><br>
  <table class="table table-bordered" id="table-add">
    <thead>
      <tr><th>Category</th><th>Equipment</th><th>Qty</th><th>Unit Cost</th><th>Total Cost</th><th></th></tr>
    </thead>
    <tbody>
      <tr>
        <th><%= collection_select(nil, :category_id, @categories, :id, :type_name, {:prompt => "Select a Category"},{:id=>'category_select',autofocus: true})%></th>
        <th><%= collection_select(nil, :equip_id, @equips, :id, :name, {:prompt => "Select an equipment"},{:id=>'equip_select'})%></th>
        <th><%=number_field_tag :quantity,1,{:class=>"quantity"}%></th>
        <th id="show_price"></th>
        <th id="total"></th>
        <%= hidden_field_tag :flag,"set"%>
        <th><button id="clk" class="btn btn-primary">Add To Bill</button></th>
      </tr>
    </tbody>
  </table>
  <div id="bill">
    <table class="table table-bordered" style="border-bottom:1px solid black;">
      <thead>
        <th>Category</th>
        <th>Equipment</th>
        <th>Qty</th>
        <th>Unit Cost</th>
        <th>Total Cost</th>
        <th></th>
      </thead>
      <tbody class="bill_item">
      <% @val=Temp.all%>
      <%@val.each do |d|%>
      <tr>
        <td><%=d.category%></td>
        <td><%=d.equip%></td>
        <td><%=d.qty%></td>
        <td><%=d.unit_price%></td>
        <td><%=d.total_price%></td>
        <td><%=link_to 'Delete',"/delete_item/#{d.id}",method: :post,:class=>"btn btn-small btn-danger",:id=>"delete"%></td>
      </tr>
      <%end%>
      <tr><td style="font-weight:bold;">Total</td><td></td><td></td><td></td><td style="font-weight:bold;">&#8377;<%=Sum.find(1).total%></td></tr>
      <br><br>
      </tbody>
    </table>
    </div>
  <%=link_to 'PRINT',receptionnist_print_path,method: :post,:class=>"btn btn-info",:id=>"print"%>
  <%=link_to 'CANCEL',receptionnist_cancel_path,method: :post,:class=>"btn btn-danger"%>
 <script type="text/javascript">
  $(document).ready(function(){
    $('#category_select').change(function(){
     $.ajax({
      url: "<%= update_equip_path %>",
      data :{
        category_id: $("#category_select").val()
      },
      dataType:"script"
     });
    });
   $('#equip_select').change(function(){
      $.ajax({
        url:"<%=cost_select_path%>",
        data:{
          equip_id: $('#equip_select').val()
        },
        dataType: "script"
      });
   });
   $('.quantity').change(function(){
      var x=parseFloat($('#unit_price').val());
      var y=parseFloat($(this).val());
      x=x*y;
      $('#total_price').val(parseFloat(x).toFixed(2));
   });
  $('#clk').on("click",function(){
    if($('#unit_price').val()!=""&&$("#total_price").val()!="")
    {
     $.ajax({ 
      url: "<%= temp_add_path %>",
      data:{
        category_id : $('#category_select').val(),
        equip_id : $('#equip_select').val(),
        quantity : $('.quantity').val(),
        unit_cost : $("#unit_price").val(),
        total_cost : $('#total_price').val(), 
      },
      dataType:"script"
    });
   }
    window.reload();
  });
  $('#print').on("click",function(){
     $.ajax({
      url:"<%= receptionnist_billno_path%>",
      data:{
        bill_no:"<%=@bill_no.to_s%>"
      },
      dataType:"script"
     });
     $('#table-add').hide();
     $('body').css('font-size','16px');
     $('input').css('border','0px');
     $('#hos_name').show().text("MAVELIKKARA DISTRICT HOSPITAL");  
     $('.btn').hide();
     $('#bill').animate({
      'marginTop':"-=60px"
     });
     $('#bill_no').show();  
     $("#hello").hide();
     $(this).hide();
     $("#submit").hide();
     $("#logout").hide();
     window.print();
  });
});
</script>
</body> 
</html> 

app/views/receptionnist/show_price.js.erb
$('#show_price').html('<%=escape_javascript(number_field_tag :unit_price ,@cost,:disabled=>true)%>');
$('#total').html('<%=escape_javascript(text_field_tag :total_price ,@cost,:disabled=>true)%>');

app/views/receptionnist/temp_add.js.erb
$('#category').append('<%=escape_javascript(text_field_tag :category ,@temp.category,:disabled=>true)%>');
$('#equipment').append('<%=escape_javascript(text_field_tag :equipment ,@temp.equip,:disabled=>true)%>');
$('#qty').append('<%=escape_javascript(number_field_tag :qty ,@temp.qty,:disabled=>true)%>');
$('#unit_cost').append('<%=escape_javascript(number_field_tag :unit ,@temp.unit_price,:disabled=>true)%>');
$('#total_cost').append('<%=escape_javascript(number_field_tag :total ,@temp.total_price,:disabled=>true)%>');
$('#remove').append("<button id='delete'>delete</button>");
window.location.reload();

app/views/receptionnist/update_equip.js.erb
$('#equip_select').html("<%= escape_javascript(options_for_select(@equips)) %>");