config/routes.rb
Rails.application.routes.draw do
  root "user#index" 
  get "user/index"     => 'user#index'
  post "user/sign_in"  => 'user#sign_in'
  get "user/sign_out" =>'user#sign_out'
  
  get"supervisor/index"  => 'supervisor#index'
  get "receptionnist/index"  => 'receptionnist#index'

  post "supervisor/creat" => 'user#creat_receptionist'
  get "supervisor/new_rec" => 'supervisor#creat'
  get "supervisor/update" => 'supervisor#update'
  post "supervisor/getupdate" => 'user#update'
  get  "supervisor/show_receptionist" => 'supervisor#show_receptionist'
  post "supervisor/add_type" => 'supervisor#add_equipment_type'
  get "supervisor/add_equip_type"=>'supervisor#add_equip_type' 
  get "supervisor/back"=>'supervisor#back'
  post "supervisor/add_equipattr"=>'supervisor#add_equipattr'
  get "supervisor/show_equipment" =>'supervisor#show_equip'
  get "supervisor/show_select" => 'supervisor#show_select'
  
  get  "equipment/update/:id"=>'equip#update_cost'
  get  "equipment/update_bpl/:id"=>'equip#update_cost_bpl'
  get "equipment/update_othr/:id"=>'equip#update_cost_othr'
  post "equipment/new_cost" => 'equip#new_cost'
  post "equipment/new_cost_othr" => 'equip#new_cost_othr'
  post "equipment/new_cost_bpl" => 'equip#new_cost_bpl'
  post "equipment/delete/:id" =>'equip#delete'
  post "equipment/reset/:id"=>'equip#reset'

  post "receptionnist/delete/:id"=>'receptionnist#delete'
  post "receptionnist/index"=> 'receptionnist#index'

  post "person/bill"=>'person#bill'
  get "update_equip"=>'receptionnist#update_equip'
  get "cost_select"=>'receptionnist#show_price'
  get "temp_add"=>'receptionnist#temp_add'
  post "delete_item/:id"=>'receptionnist#delete_item'
  post "receptionnist/print"=>'receptionnist#print'
  post "receptionnist/cancel"=>'receptionnist#cancel'
  get "receptionnist/billno"=>'receptionnist#billno'
  post "person/billcancel"=>'person#billcancel'

  get "update_billequip"=>'person#update_billequip'
  get "cost_billselect"=>'person#cost_billselect'
  get "cancel"=>'person#cancel'
  get "report_yearly"=>'category#report_yearly'
  get "report_monthly"=>'category#report_monthly'
  get "report_daily" =>'category#report_daily'

end

app/models/people.rb
class People < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
 def bill
 	 @temp_person=Tempperson.find(1)
     @temp_person.update(person_params)
     if !@temp_person.save
     	#flash[:notice]="temp person saved"
     	flash[:error]="can't save"
     end
     redirect_to :back
 end
 def billcancel
		if(params[:flag])
	     
		end
		@categories=Category.all
		@equips=Equip.all
		if params[:billno]
        	@person=Person.find_by_billno(params[:billno])
        	if @person
				     session[:billno]=params[:billno]
			    else
	    		   flash[:error]="You trying to enter #{DateTime.strptime(params[:billno],'%s')} dated bill,try something correct....!"
	    		   redirect_to :back
    		  end
 		end
 end
 def update_billequip
 		category=Category.find(params[:category_id])
 		@equips=category.equips.map { |e| [e.name,e.id] }.insert(0,"select an equipment")
 end
 def cost_billselect
  p=Person.find_by_billno(session[:billno])
  if p.bench=="apl"
 		@cost=Equip.find(params[:equip_id]).cost
  elsif p.bench=="bpl"
    @cost=Equip.find(params[:equip_id]).bpl
  else
    @cost=Equip.find(params[:equip_id]).other
  end
 end
 def cancel
 	   @person=Person.find_by_billno(session[:billno])
 	   @person.cost=@person.cost-params[:total_cost].to_i
 	   if @person.cost>=0
 	       @person.save
 	   end
       @equip=Equip.find(params[:equip_id])
       @equip.usage=@equip.usage-params[:quantity].to_i
       if @equip.usage>=0
           @equip.save
       end
       @category=Category.find(params[:category_id])
       @qty=params[:quantity].to_i
       @unit_price=params[:unit_cost]
       @total_price=params[:total_cost]

       fd=File.open("cencel.txt","a")
       fd.write("/////////////BILL NO:-")
       fd.write(session[:billno])
       fd.write("//////////////////\n")
       fd.write("***Product Canceld(Ctegory/Equipment/Qunatity/Unit Price/Total Price/Reason)***\n") 
       fd.write(Category.find(params[:category_id]).type_name)
       fd.write("\t")
       fd.write(Equip.find(params[:equip_id]).name)
       fd.write("\t")
       fd.write(params[:quantity])
       fd.write("\t")
       fd.write(params[:unit_cost])
       fd.write("\t")
       fd.write(params[:total_cost])
       fd.write("\t")
       fd.write(params[:reason])
       fd.write("\n")
 end
  private
   def person_params
    params.require(:person).permit(:name,:age,:gender,:bench,:opno,:ipno,:wardno,:address)
   end
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/person/billcancel.html.erb
<html>
<head>   
</head>
<body>
  <div id="content">
	<%=link_to "back",receptionnist_index_path,:class=>"btn btn-small btn-primary"%>
	<p id="error" style="color:red;font-weight:bold;"></p>
	<h3>Select the equipment and quantity as per bill file(bill number.txt)</h3>	
	<div style="float:right;">
		<h5 id="reason-head">Reason for cancellling the equipment</h5>
		<%=text_area_tag :reason,"",{:id=>"reason"}%>
	</div>
	<table class="table table-bordered" id="table-add">
    	<thead>
      	<tr><th>Category</th><th>Equipment</th><th>Qty</th><th>Unit Cost</th><th>Total Cost</th><th></th></tr>
    	</thead>
    	<tbody>
      	<tr>
       	 	<th><%= collection_select(nil, :category_id, @categories, :id, :type_name, {:prompt => "Select a Category"},{:id=>'category_select',autofocus: true})%></th>
        	<th><%= collection_select(nil, :equip_id, @equips, :id, :name, {:prompt => "Select an equipment"},{:id=>'equip_select'})%></th>
       		<th><%=number_field_tag :quantity,1,{:class=>"quantity"}%></th>
        	<th id="show_price"></th>
       		<th id="total"></th>
        	<%= hidden_field_tag :flag,"set"%>
        	<th><button id="clk">cancel-</button></th>
      	</tr>
    	</tbody>
  	</table>
  	<h3>Canceled Items</h3>
  	<table class="table table-bordered" style="border-bottom:1px solid black;">
      	<thead>
        	<th>Category</th>
        	<th>Equipment</th>
        	<th>Qty</th>
        	<th>Unit Cost</th>
        	<th>Total Cost</th>
        	<th></th>
      	</thead>
      	<tbody class="bill_item">
      	<tr>
        	<td id="category"></td>
        	<td id="equipment"></td>
        	<td id="qty"></td>
        	<td id="unit_cost"></td>
        	<td id="total_cost"></td>
      	</tr>
      	</tbody>
    	</table>
    </div>
    <div id="editor"></div>
  <script type="text/javascript">
    $(document).ready(function(){
    	$('#category_select').change(function(){
     		$.ajax({
     	 		url: "<%= update_billequip_path %>",
      			data :{
        			category_id: $("#category_select").val()
     			 },
      			dataType:"script"
     		});
    	});
   		$('#equip_select').change(function(){
     		 $.ajax({
        	 url:"<%=cost_billselect_path%>",
        	 data:{
          		equip_id: $('#equip_select').val()
        	 },
        	 dataType: "script"
      		});
   		});
   		$('.quantity').change(function(){
      		var x=parseFloat($('#unit_price').val());
      		var y=parseFloat($(this).val());
      		x=x*y;
      		$('#total_price').val(parseFloat(x).toFixed(2));
   		});
   		$('#clk').on("click",function(){
    	if($('#reason').val().length>=10)
     		{
    			$.ajax({ 
      			url: "<%= cancel_path %>",
      			data:{
        			category_id : $('#category_select').val(),
        			equip_id : $('#equip_select').val(),
        			quantity : $('.quantity').val(),
        			unit_cost : $("#unit_price").val(),
        			total_cost : $('#total_price').val(), 
        			reason :$('#reason').val()
     		 	},
      			dataType:"script"
    			});
    		$('#reason').val("");
    		$('#error').html("");
           }
     	else if($('#reason').val().length<10)
    		 {
     			$('#reason').css({"border-color":"red","border-width":"3px"});
     			$('#reason-head').css("color","red");
     			$("#error").html("ERROR:Reason should contain atleast 10 letters ");
    		 }
     	else
      		{
         		$("#error").html("ERROR:Reason Can't Leave Empty ");
     		 }
 		});
	});
   </script>
   </body>
   </html>

app/views/person/cancel.js.erb
$('#category').append('<%=escape_javascript(text_field_tag :category ,@category.type_name,:disabled=>true)%>');
$('#equipment').append('<%=escape_javascript(text_field_tag :equipment ,@equip.name,:disabled=>true)%>');
$('#qty').append('<%=escape_javascript(number_field_tag :qty ,@qty,:disabled=>true)%>');
$('#unit_cost').append('<%=escape_javascript(number_field_tag :unit ,@unit_price,:disabled=>true)%>');
$('#total_cost').append('<%=escape_javascript(number_field_tag :total ,@total_price,:disabled=>true)%>');

app/views/person/cost_billselect.js.erb
$('#show_price').html('<%=escape_javascript(number_field_tag :unit_price ,@cost,:disabled=>true)%>');
$('#total').html('<%=escape_javascript(text_field_tag :total_price ,@cost,:disabled=>true)%>');

app/views/person/update_billequip.js.erb
$('#equip_select').html("<%= escape_javascript(options_for_select(@equips)) %>");