config/routes.rb
Rails.application.routes.draw do
  root "user#index" 
  get "user/index"     => 'user#index'
  post "user/sign_in"  => 'user#sign_in'
  get "user/sign_out" =>'user#sign_out'
  
  get"supervisor/index"  => 'supervisor#index'
  get "receptionnist/index"  => 'receptionnist#index'

  post "supervisor/creat" => 'user#creat_receptionist'
  get "supervisor/new_rec" => 'supervisor#creat'
  get "supervisor/update" => 'supervisor#update'
  post "supervisor/getupdate" => 'user#update'
  get  "supervisor/show_receptionist" => 'supervisor#show_receptionist'
  post "supervisor/add_type" => 'supervisor#add_equipment_type'
  get "supervisor/add_equip_type"=>'supervisor#add_equip_type' 
  get "supervisor/back"=>'supervisor#back'
  post "supervisor/add_equipattr"=>'supervisor#add_equipattr'
  get "supervisor/show_equipment" =>'supervisor#show_equip'
  get "supervisor/show_select" => 'supervisor#show_select'
  
  get  "equipment/update/:id"=>'equip#update_cost'
  get  "equipment/update_bpl/:id"=>'equip#update_cost_bpl'
  get "equipment/update_othr/:id"=>'equip#update_cost_othr'
  post "equipment/new_cost" => 'equip#new_cost'
  post "equipment/new_cost_othr" => 'equip#new_cost_othr'
  post "equipment/new_cost_bpl" => 'equip#new_cost_bpl'
  post "equipment/delete/:id" =>'equip#delete'
  post "equipment/reset/:id"=>'equip#reset'

  post "receptionnist/delete/:id"=>'receptionnist#delete'
  post "receptionnist/index"=> 'receptionnist#index'

  post "person/bill"=>'person#bill'
  get "update_equip"=>'receptionnist#update_equip'
  get "cost_select"=>'receptionnist#show_price'
  get "temp_add"=>'receptionnist#temp_add'
  post "delete_item/:id"=>'receptionnist#delete_item'
  post "receptionnist/print"=>'receptionnist#print'
  post "receptionnist/cancel"=>'receptionnist#cancel'
  get "receptionnist/billno"=>'receptionnist#billno'
  post "person/billcancel"=>'person#billcancel'

  get "update_billequip"=>'person#update_billequip'
  get "cost_billselect"=>'person#cost_billselect'
  get "cancel"=>'person#cancel'
  get "report_yearly"=>'category#report_yearly'
  get "report_monthly"=>'category#report_monthly'
  get "report_daily" =>'category#report_daily'

end

app/models/equip.rb
class Equip < ActiveRecord::Base
	belongs_to :category
	validates :serial_no, presence:true, uniqueness:true, allow_blank:false
	validates :name, presence:true, uniqueness:true, allow_blank:false
	validates :cost, presence:true, allow_blank:false
	validates :bpl, presence:true, allow_blank:false
	validates :other, presence:true, allow_blank:false
	validates :category_id, presence:true, allow_blank:false
	validates_numericality_of :usage, :greater_than_or_equal_to => 0
end

app/controllers/equip_controller.rb
class EquipController < ApplicationController
include UserHelper
def update_cost
   session[:cost]=params[:id]
end
def update_cost_bpl
   session[:bpl]=params[:id]
end
def update_cost_othr
   session[:othr]=params[:id]
end
def new_cost
	 nid=session[:cost]
	 #flash[:notice]="new_change=#{change}"
	 new_change=Equip.find_by_id(nid)
	 new_change.cost =params[:ncost]
	 if new_change.save
	 	flash[:notice]="successfully updated"
	 else
        flash[:notice]=new_change.errors.full_messages.to_sentence
     end
	redirect_to :back
end
def new_cost_othr
	nid=session[:othr]
	 #flash[:notice]="new_change=#{change}"
	 new_change=Equip.find_by_id(nid)
	 new_change.other =params[:ncost_othr]
	 if new_change.save
	 	flash[:notice]="successfully updated"
	 else
        flash[:notice]=new_change.errors.full_messages.to_sentence
     end
	redirect_to :back
end
def new_cost_bpl
	nid=session[:bpl]
	 #flash[:notice]="new_change=#{change}"
	 new_change=Equip.find_by_id(nid)
	 new_change.bpl =params[:ncost_bpl]
	 if new_change.save
	 	flash[:notice]="successfully updated"
	 else
        flash[:notice]=new_change.errors.full_messages.to_sentence
     end
	redirect_to :back
end
def delete
	nid=Equip.find_by_id(params[:id])
	if nid.destroy
       flash[:notice]="successfully destroyed"
    else
       flash[:error]="error"
   end
	redirect_to :back
end
def reset
	current_id=Equip.find_by_id(params[:id])
	current_id.usage=0
	if current_id.save
		flash[:notice]="Successfully reset to zero"
	else
		flash[:error]="Errors while resetting"
	end
	redirect_to :back
end
end

app/helpers/equip_helper.rb
module EquipHelper
end

app/views/equip/update_cost.html.erb
<h1>enter the new cost</h1>
<%= link_to supervisor_show_equipment_path,:class=>"btn btn-primary" do%>
   <span>back</span>
   <%end%>
<%= form_tag(equipment_new_cost_path, method: :post) do%>
     <%=label_tag :new_cost %><br>
     <%= number_field_tag :ncost %><br><br>
     <%=submit_tag "Go!",:class=>"btn btn-success" %>
  <%end%>

app/views/equip/update_cost_bpl.html.erb
<h1>enter the new cost</h1>
<%= link_to supervisor_show_equipment_path,:class=>"btn btn-primary" do%>
   <span>back</span>
   <%end%>
  <%= form_tag(equipment_new_cost_bpl_path, method: :post) do%>
     <%=label_tag :new_cost %><br>
     <%= number_field_tag :ncost_bpl %><br><br>
     <%=submit_tag "Go!",:class=>"btn btn-success" %>
  <%end%>

app/views/equip/update_cost_othr.html.erb
<h1>enter the new cost</h1>
<%= link_to supervisor_show_equipment_path,:class=>"btn btn-primary" do%>
   <span>back</span>
   <%end%>
<%= form_tag(equipment_new_cost_othr_path, method: :post) do%>
     <%=label_tag :new_cost %><br>
     <%= number_field_tag :ncost_othr %><br><br>
     <%=submit_tag "Go!",:class=>"btn btn-success" %>
  <%end%>